development:
  cloud_name: techvision
  api_key: <%= Figaro.env.database_api_key %>
  api_secret: <%= Figaro.env.database_api_secret %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: techvision
  api_key: <%= Figaro.env.database_api_key %>
  api_secret: <%= Figaro.env.database_api_secret %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: techvision
  api_key: <%= Figaro.env.database_api_key %>
  api_secret: <%= Figaro.env.database_api_secret %>
  enhance_image_tag: true
  static_file_support: false