default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <root>
  password: <mysql_user_password>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: TechVision
